### ISSUE TITLE
[BUG] apigeecli apis clone not replacing the basepath

### ISSUE THREAD

**Issue by marcikicn** [apigee/apigeecli#606] opened 2024-12-09 09:42 UTC
**Describe the bug**
apigeecli apis clone is not replacing the basepath if basepath tag in API Proxy has more then one segment. For example:
<BasePath>/v1/initial-basepath</BasePath>

**Version**
apigeecli_v2.7.1

**To Reproduce**
  apigeecli apis clone \
    --proxy-folder apiproxies/$PROXY_NAME/apiproxy\
    --name test \
    --basepath /new-basepath\
    --org *** \
    --default-token
<BasePath>/v1/initial-basepath</BasePath>
**Expected behavior**
Created API proxy with configuration:
{
	"basepaths": [
		"/new-basepath"
	],
	...
}

**Comment by srinandan** [comment] 2024-12-09 15:59
I wasn't able to reproduce the problem:

```
apigeecli apis clone -b /new-httpbin -n new-httpbin -f ./test/apiproxy --default-token
{
	"basepaths": [
		"/new-httpbin"
	],
	"configurationVersion": {
		"majorVersion": 4
	},
	"createdAt": "1733759769840",
	"displayName": "test",
	"entityMetaDataAsProperties": {
		"subType": "Proxy",
		"createdAt": "1733759769840",
		"lastModifiedAt": "1733759769840",
		"bundle_type": "zip"
	},
	"lastModifiedAt": "1733759769840",
	"name": "new-httpbin",
	"proxies": [
		"default"
	],
	"proxyEndpoints": [
		"default"
	],
	"resourceFiles": {},
	"targetEndpoints": [
		"default"
	],
	"targets": [
		"default"
	],
	"type": "Application",
	"revision": "1"
}
```

The sample proxy is included in the test folder of the repo.

Version
```
apigeecli --version
apigeecli version 2.7.1 date: 2024-12-05T23:01:06Z [commit: ef1fda1]
```

**Comment by marcikicn** [comment] 2024-12-09 16:18
Sample proxy in the the test folder of the repo - test_proxy.zip hase BasePath tag set to /test with only one segment of URI. Issue appears only if BasePath has more than one segments. For example: /v1/test.
Thank you

**Comment by srinandan** [comment] 2024-12-09 17:50
I tried it with two segments like so and it still worked:

```
apigeecli apis clone -b /v1/new-httpbin -n new-httpbin -f ./test/apiproxy --default-token
{
	"basepaths": [
		"/v1/new-httpbin"
	],
	"configurationVersion": {
		"majorVersion": 4
	},
	"createdAt": "1733766602730",
	"displayName": "test",
	"entityMetaDataAsProperties": {
		"lastModifiedAt": "1733766602730",
		"bundle_type": "zip",
		"subType": "Proxy",
		"createdAt": "1733766602730"
	},
	"lastModifiedAt": "1733766602730",
	"name": "new-httpbin",
	"proxies": [
		"default"
	],
	"proxyEndpoints": [
		"default"
	],
	"resourceFiles": {},
	"targetEndpoints": [
		"default"
	],
	"targets": [
		"default"
	],
	"type": "Application",
	"revision": "1"
}```

**Comment by srinandan** [comment] 2024-12-09 17:51
Three segments also worked: 

```
apigeecli apis clone -b /v1/api/new-httpbin -n new-httpbin2 -f ./test/apiproxy --default-token
{
	"basepaths": [
		"/v1/api/new-httpbin"
	],
	"configurationVersion": {
		"majorVersion": 4
	},
	"createdAt": "1733766677128",
	"displayName": "test",
	"entityMetaDataAsProperties": {
		"createdAt": "1733766677128",
		"lastModifiedAt": "1733766677128",
		"bundle_type": "zip",
		"subType": "Proxy"
	},
	"lastModifiedAt": "1733766677128",
	"name": "new-httpbin2",
	"proxies": [
		"default"
	],
	"proxyEndpoints": [
		"default"
	],
	"resourceFiles": {},
	"targetEndpoints": [
		"default"
	],
	"targets": [
		"default"
	],
	"type": "Application",
	"revision": "1"
}
```

**Comment by srinandan** [comment] 2024-12-09 17:53
...and with the zip

```
apigeecli apis clone -b /v1/api/new-httpbin -n new-httpbin2 -p ./test/test_proxy.zip --default-token
{
	"basepaths": [
		"/v1/api/new-httpbin"
	],
	"configurationVersion": {
		"majorVersion": 4
	},
	"createdAt": "1733766791486",
	"displayName": "test",
	"entityMetaDataAsProperties": {
		"bundle_type": "zip",
		"subType": "Proxy",
		"createdAt": "1733766791486",
		"lastModifiedAt": "1733766791486"
	},
	"lastModifiedAt": "1733766791486",
	"name": "new-httpbin2",
	"proxies": [
		"default"
	],
	"proxyEndpoints": [
		"default"
	],
	"resourceFiles": {},
	"targetEndpoints": [
		"default"
	],
	"targets": [
		"default"
	],
	"type": "Application",
	"revision": "1"
}
```

**Comment by srinandan** [comment] 2024-12-11 21:24
Closing this issue. please re-open if the cli is not working as expected.

**Closed by srinandan** 2024-12-11 21:24 UTC

**Comment by clhodapp** [comment] 2025-10-23 22:11
I experienced this and reduced it. The behavior occurs due to the regex here: https://github.com/apigee/apigeecli/blob/35e499a59fc1f86bcf15af22c0803c287d572854/internal/cmd/apis/cloneapi.go#L234

Essentially, your initial base path has to match the regex `\/\w+`, which is (IMO) over-limited, as it's fairly likely that it'll have at least dashes and more slashes in it.

After changing my initial base path from a "reasonable default" value to `/replaced`, the replacement occurred as expected.
