### ISSUE TITLE
Latest release 1.112 fails to run on Mac.

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigeecli#98] opened 2022-10-10 19:17 UTC
On a Mac running macOS Monterey Version 12.6 the command returns
```
apigeecli -v
Killed: 9
```

**Comment by srinandan** [comment] 2022-10-10 19:28
did you install via the downloadLatest script? What is the processor type?

**Comment by kurtkanaskie** [comment] 2022-10-10 19:49
Both via the installer script and manually.

apigeecli_v1.112_Darwin_x86_64/apigeecli

**Comment by ssvaidyanathan** [comment] 2022-10-10 19:58
+1 - I see the same issue
the Linux version seem to work
The issue with the MacOS is - `cannot be opened because it is from an unidentified developer`

**Comment by kurtkanaskie** [comment] 2022-10-10 20:06
No, that's not the issue.
If you right-click on the executable, then select open in the Finder, then close, you'll then be able to run it.
Or try to run it.

Nandan is working on it.

**Comment by srinandan** [comment] 2022-10-11 04:24
The problem was [upx](https://github.com/upx/upx). I'm using version 3.96, which also happens to be the latest. I have removed upx for all version (even though it worked for linux.

@ssvaidyanathan confirmed it works for him. Please try this [binary](https://github.com/apigee/apigeecli/releases/tag/v1.113.5-beta). I may have a new release v1.113 since this is impacting many users.

**Comment by kurtkanaskie** [comment] 2022-10-11 13:21
Already checked, it works fine.

Regards,
Kurt


Kurt Kanaskie

*apigee <https://apigee.com/api-management/>* | Technical Solution
Consultant - Specialist CE - BAP CoE

***@***.***

484 695 1106

**Comment by srinandan** [comment] 2022-10-11 19:50
This is fixed in v1.113

**Closed by srinandan** 2022-10-11 19:50 UTC
